### PR TITLE
Update Code-Style-Guide.md

### PR DESCRIPTION
**Pull request by deavmi**

### CODE REVIEW

**Comment by MathJud** [comment]
As the word 'Example' is located at the beginning of a sentence it should IMHO start with an upper case letter.

**Comment by deavmi** [comment]
Yes it should.

**Comment by deavmi** [comment]
That's what my commit contains tho.

**Comment by deavmi** [comment]
Are you going to merge this?

**Comment by MathJud** [comment]
Oh, sorry that I closed this one.
All fine, I merged it manually into qaul-ng.

**Comment by deavmi** [comment]
Okay. cool. :)

**Pull request closed without merging**
