### PR TITLE
Code highlighting added.

### PR DESCRIPTION
**Pull request by deavmi**

### CODE REVIEW

**Comment by MathJud** [comment]
Where do you see the advantage of this change?

**Comment by deavmi** [comment]
Looks more processional.

**Comment by deavmi** [comment]
* professional

**Comment by MathJud** [comment]
You're right, there is a formatting error!
But it's the other way round: Everything indented should be formatted as code and not as titles, even when it has a '#' in front of it.

**Comment by deavmi** [comment]
Okay.

**Comment by deavmi** [comment]
Should I fix something here or close this PR?

**Comment by MathJud** [comment]
It would be cool, if you like to do that. It would be great, everything that is indented should be wrapped as a whole in the markdown tag for code.

**Comment by deavmi** [comment]
@MathJud I wanted to know. Is the iOS version still being developed?

**Comment by deavmi** [comment]
What changes should I make to this file? @MathJud

**Comment by MathJud** [comment]
I fixed this with commit 71cf777ff2f2cbd2a39ca18e90224be5233a564d

**Pull request closed without merging**
